version: 0.0.1

methodology: network_validation   # technique used in the validation:
                                  # - network_validation: to validate a single network file specified in    "network_validation" block

datasets:
  demand: ["ourworldindata"]  # list of datasets sources to use. A subset of 'ourworldindata'
  installed_capacity: ["irena"]  # list of datasets sources to use. A subset of 'irena'
  # energy_dispatch: []  # list of datasets sources to validate energy dispatch. Not yet supported
  # network: []  # list of datasets sources to validate networks. Not yet supported

network_validation:
  network_path: "/home/mwiche/pypsa-earth-status/workflows/pypsa-zambia/networks/elec_s_10_ec_lcopt_Co2L-3h.nc" # File to the PyPSA network file to validate
  year: [2021]  # year of the network to validate
  countries: ['ZM', 'ZW', 'TZ', 'MZ', 'MW', 'CD', 'AO', 'BW', 'NA']  # country of the network to validate
  shapefile: False
