version: 0.0.1

methodology: network_validation   # technique used in the validation:
                                  # - network_validation: to validate a single network file specified in    "network_validation" block

datasets:
  demand: ["ourworldindata"]  # list of datasets sources to use. A subset of 'ourworldindata'
  installed_capacity: ["irena"]  # list of datasets sources to use. A subset of 'irena'
  # energy_dispatch: []  # list of datasets sources to validate energy dispatch. Not yet supported
  # network: []  # list of datasets sources to validate networks. Not yet supported

network_validation:
  network_path: "resources/example_DE.nc" # File to the PyPSA network file to validate
  year: [2021]  # year of the network to validate
  countries: ['DE', 'FR']  # country of the network to validate
  shapefile: false
  validate_cross_border_capacity: true # validation of cross border capacity

inflow_validation:
  run: "validation_dispatch_zambia_2024" # matches resources/{run}/ from workflow directory
  grdc_station: "KAFUE HOOK BRIDGE (60334669)"
  glofas_dx: 0.05
  grdc_dx: 1.0
  k_scale: 8.5
  validation_ppl_idx: 0
  ppl_bbox:
    lat_min: -17
    lat_max: -15.5
    lon_min: 28
    lon_max: 29
